### ISSUE TITLE
Use MaterialBanner with Theme.AppCompat

### ISSUE THREAD

**Issue by Remicek** [sergivonavi/MaterialBanner#2]
> In order to use this banner your app theme should inherit from a Material Components theme.

Is it possible to use Material banner without changing the basic application theme to 
`Theme.MaterialComponents` for example importing only required styles/resources from MaterialComponents?

Banner component is working as expected, but I cannot afford to change all styles in my app...

**Comment by sergivonavi** [comment]
Yes, but only if you create a banner dynamically.

Use the second constructor `Banner.Builder(Context, int)` in order to set a Material theme.

```
Banner banner = new Banner.Builder(context, R.style.MyBannerTheme)
...
```

where `R.style.MyBannerTheme` is a custom theme inherited from one of the `Theme.MaterialComponents`. And you can change here some attributes:

```
<style name="MyBannerTheme" parent="Theme.MaterialComponents">
    <item name="colorPrimary">@color/colorPrimary</item>
    <item name="colorSurface">@color/colorSurface</item>
    <item name="colorOnSurface">@color/colorOnSurface</item>
    <item name="bannerStyle">@style/MyBannerStyle</item>
</style>
```

This theme will only affect the banner's appearance.

For additional styling guide, please, refer to [MaterialBanner - Styling](https://github.com/sergivonavi/MaterialBanner#styling).

If you have any further questions don't hesitate to ask :)

**Comment by Remicek** [comment]
Perfekt, that was what I needed :)
